worker_processes auto;
pid /run/nginx/nginx.pid;
error_log /dev/stderr;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    access_log /dev/stdout;
    sendfile on;

    server {
        listen 80;
        root /usr/share/nginx/html;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }

        location /api/ {
            proxy_pass ${API_SCHEME}://${API_HOST}/api/;
            proxy_ssl_server_name on;
            proxy_http_version 1.1;
            proxy_set_header Host ${API_HOST};
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_buffering off;
            proxy_read_timeout 120s;
        }

        location = /healthz {
            access_log off;
            return 200 'ok';
            add_header Content-Type text/plain;
        }
    }
}
